### ISSUE TITLE
If I Ran A Station

### ISSUE THREAD

**Issue by melodykramer** [lisawilliams/community#1]
These two pieces seem relevant for your reading list

http://melodykramer.github.io/2015/05/14/if-I-ran-a-station/

http://melodykramer.github.io/2015/05/20/whats-the-point-of-local/

**Comment by lisawilliams** [comment]
AH  Many thanks, Melody!

**Comment by lisawilliams** [comment]
I also want to include the less often discussed possibilities for engagement that you have been bringing up in your work.  When I talk to people in the industry about engagement, it almost always means three things: online engagement, RL events, and $$, which seems to me a rather impoverished list.

**Comment by lisawilliams** [comment]
Melody, I've added your contributions.  Thank you so much!  Here's the commit:

https://github.com/lisawilliams/community/commit/907aa9d43a61da8b844d560db5fe523db0922f93
